# Generated by Django 3.1 on 2020-08-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('cuisines', models.CharField(max_length=50)),
                ('timings', models.TextField()),
                ('url', models.TextField()),
                ('address', models.TextField()),
                ('phone_number', models.TextField()),
                ('has_online_delivery', models.TextField()),
                ('is_delivering_now', models.TextField()),
                ('average_cost_for_two', models.PositiveIntegerField()),
                ('highlights', models.JSONField()),
                ('images', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField()),
                ('url', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
